<a href="https://colab.research.google.com/github/Anyulund/Python-practice/blob/main/MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Transpose Matrix


For every cell result[i][j] we need to replace the value with  input[j][i] 
where input is the matrix to be transposed and 
result is the placeholder for the transposed matrix

i = row /n
j = column placeholder in a row



In [ ]:
inputMatrix = [[0,0,1],
               [0,1,0],
               [0,1,1]]
initMatrix = [[0 for row in range(len(inputMatrix))]for col in range(len(inputMatrix))]

In [ ]:
for i in range(len(inputMatrix)):
  for j in range(len(inputMatrix[0])):
    initMatrix[i][j] = inputMatrix[i][j]
  print(initMatrix)

[[0, 0, 1], [0, 0, 0], [0, 0, 0]]
[[0, 0, 1], [0, 1, 0], [0, 0, 0]]
[[0, 0, 1], [0, 1, 0], [0, 1, 1]]


### Search sorted Matrix for an element



#### Bruteforce

In [ ]:
import numpy as np
target = 7
matrix = []

for row in range(3):
  row = np.random.randint(10,size=12)
  print(row)
  matrix.append(row)
print(matrix)


[9 0 6 0 7 7 3 9 6 9 4 5]
[9 5 2 1 0 3 9 0 6 9 9 3]
[6 4 0 5 1 6 4 3 4 6 2 3]
[array([9, 0, 6, 0, 7, 7, 3, 9, 6, 9, 4, 5]), array([9, 5, 2, 1, 0, 3, 9, 0, 6, 9, 9, 3]), array([6, 4, 0, 5, 1, 6, 4, 3, 4, 6, 2, 3])]


In [ ]:

def searchMatrix(matrix, target):
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
      if matrix[i][j] == target:
        return True
  return False
    
    
searchMatrix([[1,2,3],[4,5,6],[7,8,9]],6)

True

#### Binary Search 


1.   Let min = 1min=1m, i, n, equals, 1 and max = nmax=nm, a, x, equals, n.
2.   Guess the average of maxmaxm, a, x and minminm, i, n, rounded down so that it is an integer.
3.   If you guessed the number, stop. You found it!
4.   If the guess was too low, set minminm, i, n to be one larger than the guess.
5.   If the guess was too high, set maxmaxm, a, x to be one smaller than the guess.
6.   Go back to step two.



Material on how to use class

https://www.w3schools.com/python/python_classes.asp

https://www.programiz.com/python-programming/class

In [ ]:
def searchMatrixbinary(matrix, target):
    # Helper function to perform binary search for the target on a row
    def helper_search(l, target):
        start, end = 0, len(matrix[0])-1
            
        while start <= end:
            mid = (start+end)//2
            if l[mid] == target:
                return True
            elif l[mid] < target:
                start = mid + 1
            else:
                end = mid-1
        return False
            
    if matrix == [] or matrix == [[]]:
        return False
    start, end = 0 ,len(matrix)-1
        
    # outer binary search to select the row
    while start <= end:
        mid = (start + end)//2
        # inner binary search on the row
        value = helper_search(matrix[mid], target)
        if value == True:
            return True
        elif matrix[mid][-1] > target:
            end = mid-1
        else:
            start = mid + 1
    return False

In [ ]:
searchMatrixbinary([[1,2,3],[4,5,6],[7,8,9]],6)

True

#### Trasversing the Matrix 